[package]
name = "excel_xmlwriter"
description = "A simple Rust xml writer for Excel xml"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
tempfile = "3.2.0"
pretty_assertions = "1"
